name: deploy cdk stacks on aws
on:
  push:
    branches:
      - main # deploy code whenever pushed to main branch
jobs: #defin jobs
  job1: #deploy job
    runs-on: ubuntu-latest #free server from azure
  
    steps: #steps to setup cdk and run 
      - name: setup node.js version 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: checkout code
        uses: actions/checkout@v2

      - name: verify
        run: ls

      - name: install dependencies
        run:
          cd bmocdktraining
          npm install
          npm install -g aws-cdk

      - name: compile cdk code
        run:
          cd bmocdktraining
          cdk synth